### ISSUE TITLE
Spawners changing back

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [ChosenArchitect/Project-Architect#164]
In basic minecraft when you use a spawn egg on a spawner it changes what that spawner spawns. Like you can change a zombie spawner to blaze or blaze to enderman. But I tried to change 2 different spawners, many different times, both spawners were blaze spawners. I tried to change them from blaze to wither skeleton but after just one spawn they changed back to blaze spawners. Is this intentional or a bug because in basic minecraft it works but in this pack it doesn't.
**To Reproduce**
1. Find a spawner
2. Use a spawn egg (I got spawn eggs from @mobgrinding swabs)
3. Wait for first spawn 
4. See if it changes back or if it still spawns the new mob

Project architect mod pack.

**Comment by James103** [comment]
Workaround: Every time you place a spawner, you have to let it spawn its current mob at least once, then you can change the type of the spawner.

This is a vanilla bug, and it also exists in more modern Minecraft versions (including 1.18.2).
To reproduce in creative mode with cheats enabled:
1. `give @s spawner{BlockEntityTag:{SpawnData:{entity:{id:"minecraft:zombie"}},SpawnPotentials:[{weight:1,data:{entity:{id:"minecraft:zombie"}}}]}} 1`
2. `give @s skeleton_spawn_egg 1`
3. Place down the spawner.
4. Use the spawn egg on the spawner before the spawner spawns.
5. `time set night`
6. Wait until the spawner spawns for the first time.
7. Notice that the spawner reverts to its previous mob (i.e. the mob it had when it was placed)

The reason for this is because using a Spawn Egg on a spawner changes only `SpawnData` and not `SpawnPotentials`, but when a spawner spawns for the first time after being placed, if the spawner was placed and it had the `SpawnPotentials` tag, a mob from the `SpawnPotentials` tag is copied to the `SpawnData` tag right after the spawning cycle concludes.

This is reproducible in survival Minecraft with this mod pack because it
1. Provides a way to pick up spawners (through the Sack of Holding). It is very likely that the spawner would have spawned at least once and gained its `SpawnPotentials` tag, which would be kept when the spawner is in item form and later placed down.
2. Provides a way to obtain spawn eggs in survival Minecraft, through the mob_grinding_utils mod.

**Comment by DevilMayCryIfrit** [comment]
Thank you it worked sorry for taking so long had no time to play keep up the good work.
