### ISSUE TITLE
Building blocks without EMC

### ISSUE THREAD

**Issue by Beastpunisher** [ChosenArchitect/Project-Architect#38]
The Vanilla stone slabs, stone brick slabs, smooth stone slabs, end stone brick slab, glass panes do not currently have EMC

**Comment by ChosenArchitect** [comment]
Slabs and such cant have emc as you will end up with .5 of something with emc and that's not supported.

**Comment by JacobCallahan** [comment]
@Beastpunisher if you really want to emc them, hold one in your hand then run the following two commands:

- /projecte setemc <numeric value>
- /reload
As chosen said, those would have otherwise needed an emc value <1. So you can set each to 1. This is technically more expensive, but a low price to pay for convenience!
