### ISSUE TITLE
Crashes when i open the game or play for a bit.

### ISSUE THREAD

**Issue by ramonmennega** [ChosenArchitect/Project-Architect#68]
Error
Game crashed
An unexpected issue occured and the game crashed. We're sorry for the inconvenience.

This crash may be caused by an invalid java runtime configuration. Check any custom configuration settings. 

Exit code: 1

So this error happens to me everytime. After 10 tries i maybe able to play for an hour and then the pack crashes again
[hs_err_pid4012.log](https://github.com/ChosenArchitect/Project-Architect/files/8040696/hs_err_pid4012.log)
.

**Comment by plinio-jrm** [comment]
From what i've see in the logs, i can only advice you to update your Java to a recent version.
If you do `java --version` in the `command prompt`, you will see your current version. From the logs you're using Java 8, while your Java HotSpot is version 25.

For comparison, this is my `java --version` information:

> java 15.0.1 2020-10-20
> Java(TM) SE Runtime Environment (build 15.0.1+9-18)
> Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

If that doesn't solve the issue, a more expert person can give you another advice or directions.
Cheers.

**Comment by 14505alex** [comment]
I get the same thing and in java's own updater it says it is up to date

**Comment by plinio-jrm** [comment]
> I get the same thing and in java's own updater it says it is up to date

Fortunately, since i'm a developer, i tend to update it manually. I don't rely on the Updater, because it can assume you don't need a updated version to run the casual use of it. So i recommend doing it manually.

It is a pain, because sometimes you have to check system variable to see if JAVA_HOME is pointing to the right version and make sure you install 32/64 bits. There are alot of programs that use only 32bits and others that use 64bits.

Cheers.
